begin;
insert into t values (1,'2',3), (4,'5',6), (7,'8',9) on duplicate key update j = i * k, i = values(i);
replace into t values (1,'2',3), (4,'5',6), (7,'8',9);
replace into t values (4,'5',6), (7,'8',9), (1,'2',3);
replace into t values (7,'8',9), (1,'2',3), (4,'5',6);
insert into t values (1,'2',3), (4,'5',6), (7,'8',9) on duplicate key update j = i * k, i = values(i)+1;
update ignore t set i = 3 where i = 6;
delete a from t as a where i = 6;
delete a from t as a;
update ignore t set j = '3' where i = 3;
update ignore t set j = '4';
insert into t values (1,'2',3), (4,'5',6), (7,'8',9) on duplicate key update j = i * k, i = -values(i);
insert ignore into t values (1,'2',3), (4,'5',6), (7,'8',9) on duplicate key update j = i * k, i = values(i);
insert ignore into t values (1,'2',3), (4,'5',6), (7,'8',9) on duplicate key update j = i * k, i = values(i)+1;
insert ignore into t values (1,'2',3), (4,'5',6), (7,'8',9) on duplicate key update j = i * k, i = -values(i);
insert into t values (1,'2',3), (4,'5',6), (7,'8',9) on duplicate key update j = i * k, i = -values(i)+3;
commit;
